### ISSUE TITLE
Living Images Viewer kann Videos aus dGoLive wiedergeben

### ISSUE THREAD

**Issue by tjorbo** [kultursphaere-sh/Living-Images-Viewer#61]
# Story
Als PV möchte ich, dass der Living Images Viewer Videos als Living Images aus dGoLive (Dataport) abspielen kann, um die neue Infrastruktur zu nutzen.

# Technische Details

-

# Akzeptanzkriterien

- Die Videos auf der neuen Infrastruktur sind im Living Images Viewer abspielbar
- Der Living Images viewer kann unterscheiden, ob die bisherige Infrastruktur oder die neue genutzt wird und verhält sich dementsprechend anders
- Die Videos auf der alten Infrastruktur können weiterhin abgespielt werden

**Comment by tjorbo** [comment]
@93Dennis 

welches Format ist für die Living Images am besten und wird es von kaltura (dGoLive) unterstützt?

https://knowledge.kaltura.com/help/how-to-retrieve-the-download-or-streaming-url-using-api-calls

**Comment by tjorbo** [comment]
@93Dennis 

Wir haben ein erstes Video online. Ich habe mal das Format "URL" gewählt aber wir können auch andere verwenden:
https://api.dgolive.de/p/105/sp/0/playManifest/entryId/0_q4o2qodw/format/url/flavorParamId/301971/video.mp4

https://kulturfinder.sh/de/institutions/list/details/Staldgarden%20Museum%20Kolding

**Comment by tjorbo** [comment]
Informationen zum hochgeladenen Ticket: https://github.com/kultursphaere-sh/Living-Images-Viewer/issues/63

**Comment by 93Dennis** [comment]
Die dGoLive Videos funktionieren ganz normal. Da muss nur die URL im Datensatz ausgetauscht werden. 
Sobald die Daten online sind, kann ich Code einbauen, dass sie direkt vom Server gezogen werden.
